export const reverseCardEasy = [
  { idx: 0, selected: false },
  { idx: 1, selected: false },
  { idx: 2, selected: false },
  { idx: 3, selected: false },
  { idx: 4, selected: false },
  { idx: 5, selected: false },
  { idx: 6, selected: false },
  { idx: 7, selected: false },
  { idx: 8, selected: false },
  { idx: 9, selected: false },
];

export const reverseCardNormal = [
  { idx: 0, selected: false },
  { idx: 1, selected: false },
  { idx: 2, selected: false },
  { idx: 3, selected: false },
  { idx: 4, selected: false },
  { idx: 5, selected: false },
  { idx: 6, selected: false },
  { idx: 7, selected: false },
  { idx: 8, selected: false },
  { idx: 9, selected: false },
  { idx: 10, selected: false },
  { idx: 11, selected: false },
  { idx: 12, selected: false },
  { idx: 13, selected: false },
];

export const reverseCardHard = [
  { idx: 0, selected: false },
  { idx: 1, selected: false },
  { idx: 2, selected: false },
  { idx: 3, selected: false },
  { idx: 4, selected: false },
  { idx: 5, selected: false },
  { idx: 6, selected: false },
  { idx: 7, selected: false },
  { idx: 8, selected: false },
  { idx: 9, selected: false },
  { idx: 10, selected: false },
  { idx: 11, selected: false },
  { idx: 12, selected: false },
  { idx: 13, selected: false },
  { idx: 14, selected: false },
  { idx: 15, selected: false },
  { idx: 16, selected: false },
  { idx: 17, selected: false },
];
