export const data = {
  cards: [
    {
      id: 0,
      name: '우디',
      hashtags: ['카우보이', '우디_프라이드', '두손_번쩍_들어!'],
      img: 'assets/image/woody.png',
      category: 'main-character',
    },
    {
      id: 1,
      name: '버즈',
      hashtags: ['버즈_라이트이어', '우주비행사', '무한한공간_저_너머로'],
      img: 'assets/image/buz.png',
      category: 'main-character',
    },
    {
      id: 2,
      name: '제시',
      hashtags: ['카우걸', '버즈여친', '사이드킥'],
      img: 'assets/image/jessie.png',
      category: 'main-character',
    },
    {
      id: 3,
      name: '보핍',
      hashtags: ['양치기_아가씨', '양', '조명등'],
      img: 'assets/image/bopeep.png',
      category: 'etc',
    },
    {
      id: 4,
      name: '랏소',
      hashtags: ['나쁜놈', '핑크_딸기곰', '케어베어'],
      img: 'assets/image/lotso.png',
      category: 'evil',
    },
    {
      id: 5,
      name: '햄',
      hashtags: ['돼지', '저금통', '꿀꿀'],
      img: 'assets/image/hamm.png',
      category: 'etc',
    },
    {
      id: 6,
      name: '포테이토 부부',
      hashtags: ['미스터_포테토', '미스_포테토', '감자'],
      img: 'assets/image/potato.png',
      category: 'etc',
    },
    {
      id: 7,
      name: '알린',
      hashtags: ['외계인', '하~이', '트리오'],
      img: 'assets/image/alien.png',
      category: 'etc',
    },
    {
      id: 8,
      name: '포키',
      hashtags: ['포크', '눈물', '핸드'],
      img: 'assets/image/forky.png',
      category: 'new-face',
    },
  ],
};
